apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: data-0fec8a
  namespace: argo
spec:
  entrypoint: update
  podGC:
    strategy: OnWorkflowSuccess
  arguments:
    parameters:
    - name: docker-image
      value: musanaengineering/platformtools:python:1.0.0
    - name: infrastructure-repository
      value: https://github.com/musana-engineering/globorealty.git
  templates:
    - name: connection
      inputs:
        artifacts:
        - name: scripts
          path: /home/scripts
          git:
            repo: "{{workflow.parameters.infrastructure-repository}}"
            depth: 1
        volumes:
        - name: pipeline-secrets
          secret: 
            secretName: data-0fec8a
      script:
        imagePullPolicy: "Always"
        image: "{{workflow.parameters.docker-image}}"
        command: ["sh"]
        source: |

          cd /home/scripts/globorealty/scripts

        env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pipeline-secrets
              key: CLIENT_SECRET  

    - name: datastore
      inputs:
        artifacts:
        - name: scripts-plan
          path: /home/scripts
        volumes:
        - name: pipeline-secrets
          secret: 
            secretName: data-0fec8a
      script:
        imagePullPolicy: "Always"
        image: "{{workflow.parameters.docker-image}}"
        command: ["sh"]
        source: |

          export ARM_CLIENT_ID="your_azure_sp_client_id"
          export ARM_CLIENT_SECRET="$CLIENT_SECRET"
          export ARM_TENANT_ID="your_azure_tenant_id"
          export ARM_SUBSCRIPTION_ID="your_azure_subscription_id"

        env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pipeline-secrets
              key: CLIENT_SECRET  

    - name: data-asset
      inputs:
        artifacts:
        - name: scripts-plan
          path: /home/scripts
        volumes:
        - name: pipeline-secrets
          secret: 
            secretName: data-0fec8a
      script:
        imagePullPolicy: "Always"
        image: "{{workflow.parameters.docker-image}}"
        command: ["sh"]
        source: |

          export ARM_CLIENT_ID="your_azure_sp_client_id"
          export ARM_CLIENT_SECRET="$CLIENT_SECRET"
          export ARM_TENANT_ID="your_azure_tenant_id"
          export ARM_SUBSCRIPTION_ID="your_azure_subscription_id"

        env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pipeline-secrets
              key: CLIENT_SECRET  

    - name: validation
      inputs:
        artifacts:
        - name: scripts-plan
          path: /home/scripts
        volumes:
        - name: pipeline-secrets
          secret: 
            secretName: data-0fec8a
      script:
        imagePullPolicy: "Always"
        image: "{{workflow.parameters.docker-image}}"
        command: ["sh"]
        source: |

          export ARM_CLIENT_ID="your_azure_sp_client_id"
          export ARM_CLIENT_SECRET="$CLIENT_SECRET"
          export ARM_TENANT_ID="your_azure_tenant_id"
          export ARM_SUBSCRIPTION_ID="your_azure_subscription_id"

        env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pipeline-secrets
              key: CLIENT_SECRET  

    - name: update
      dag:
        tasks:
          - name: connection
            template: connection
          - name: datastore
            template: datastore
            dependencies: [connection]
          - name: data-asset
            template: data-asset
            dependencies: [connection, datastore]
          - name: validation
            template: validation
            dependencies: [connection, datastore, data-asset]